"""initial migration

Revision ID: 51ab87371b6c
Revises: 
Create Date: 2025-10-21 12:58:37.769322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ab87371b6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StringInformation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('is_palindrome', sa.Boolean(), nullable=False),
    sa.Column('unique_characters_count', sa.Integer(), nullable=False),
    sa.Column('unique_characters_list', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_StringInformation_id'), 'StringInformation', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_StringInformation_id'), table_name='StringInformation')
    op.drop_table('StringInformation')
    # ### end Alembic commands ###
